### ISSUE TITLE
Error / cmd panel opens and closes fast

### ISSUE THREAD

**Issue by HexaSeeker** [Nenkai/GTToolsSharp#6]
![Capture](https://user-images.githubusercontent.com/128065189/225944383-413a4ead-3760-42b1-8e9c-a8a909e65290.PNG)
When i open the .exe this panel appears and disappears fast, i managed to capture it.
I'm using Win7 SP1, i have NET SDK 5.0 & Core SDK 3.1 both installed, in addition to NFW 4.8.
Thanks in advance for the efforts.

**Comment by pez2k** [comment]
A console window opens and immediately closes because it's a command-line application - it has no GUI so double-clicking the exe won't do anything useful.

The message you've provided a screenshot of suggests that you don't have the 32-bit .NET 5.0 runtime installed. Make sure you're installing the right one.

You may continue to have issues though, as Windows 7 has been out of support for over 3 years now, and so .NET 5.0 does not support Windows 7 for home users.
